# Generating Shocks for <em> Tradeoffs for the poor, divine coincidence for the rich </em>

This document assists with generating and replicating similar shock series for the paper <em>Tradeoffs for the poor, divine coincidence for the rich</em> by Marco Del Negro, Ibrahima Diagne, Keshav Dogra, Pranay Gundam, Donggyu Lee, and Brian Pacula. Reach out to ibrahima.diagne@ny.frb.org if you have any questions.

### Description

As discussed in the paper, we generate 60k periods of simulated data from the model, constructed by drawing 200 300-quarter-long sequences of shocks (75 years, about the length of
the post-war period). In each of these sequences shocks are generated by a mixture: with a
probability of 1/20 (every five years on average) we have either a COVID (we use the estimated shocks from the 2021Q2-2022Q3 period) or a Great Recession (we use the estimated
shocks from 2008Q1-2009Q2) episode; otherwise shocks are drawn independently from their
estimated distribution.

Because the COVID and Great Recession shocks are large in magnitude and one-sided
(the former mostly negative supply shocks, the latter mostly negative demand shocks), we
face two challenges during simulations. First, the mean of some shocks deviates substantially
from zero due to the inclusion of COVID/Great Recession shocks. In particular, price and
wage markup shocks display large non-zero means, which can significantly affect the simulation outcomes. Second, the model sometimes exhibits explosive behavior, i.e., unrealistically
large responses of variables, when the ZLB binds, especially during periods of prolonged
expected ZLB durations. Although these explosive behaviors occur infrequently, accounting
for only a small percentage of the entire simulation, they can distort the overall simulation
results.

To address these two challenges, we implemented the following procedures in generating
shocks for the simulations. First, we introduce “cool down” shocks following any occurrence of COVID or Great Recession shocks during simulations. Specifically, each instance of
COVID or Great Recession shocks is followed by six periods of randomly generated shocks,
constructed such that their mean offsets that of the preceding shocks. Consequently, over the
12 period window, including both the COVID/Great Recession and cool down shocks, the
mean is zero by construction. Additionally, each 300 period sequence of shocks is augmented
by its sign-reversed counterpart, ensuring that the overall mean across all shocks used in the
simulations is exactly zero.

Second, to prevent a few explosive episodes from distorting the results, we exclude certain
simulated data sets from the final analysis. Specifically, we run many sets of 300 period
simulations and exclude any set in which key variables exhibit explosive behavior. We check
two variables, the consumption of the bottom 10% wealth group and the unemployment
rate, and classify their behavior as explosive if they deviate from their respective steady
state values by more than 1,500%.

### Using <code> simulate_shock_spec.m </code>

#### A. Shocks used 
<ol>
<li><em> Q.E.</em> (zeroed-out)li>
<li><em> Fixed cost </em></li>
<li><em> Risk premia </em></li>
<li><em> Productivity (TFP)</em></li>
<li><em> Lump-sum transfer</em></li>
<li><em> Discount factor</em></li>
<li><em> Monetary policy</em> (zeroed-out)</li>
<li><em> Investment technology</em></li>
<li><em> Price mark-up </em></li>
<li><em> Wage mark-up </em></li>
</ol>

We generate a sequence of i.i.d mean-zero shocks distributed with respect to a multivariate random normal with a specified covariance matrix. These initial, or "raw," shocks are 600k periods long and are trimmed to obtain a finalized 60k period shock series in the file <code> simulate_shock_spec.m </code>.

#### B. Trimming scheme (shock_series_combined_hk_5)

To generate a similar shock series to that provided, <code> shock_series_combined_hk_5.mat</code>, a multi-stage trimming scheme is implemented to prevent instances where key variables exhibit explosive behavior. To initialize the trimming, set <code>generate_noCovidGR=true</code>. Set <code>kappa=0.1</code> (the highest value for the slope of the Taylor-type monetary policy rule that we analyze in the paper). Set <code> phi_pi_seq = [4, 1.5, 4]</code> (sequence of inflation response parameter values used in trimming). Lastly, we specify an upper range for the number of ZLB periods that should occur in each 300 period block of shocks in the setting <code>ELB_threshold</code>.
<ul>

<li> Trim 1: $\phi_\pi$ is set to 4. At this stage, COVID and Great Recession shocks are drawn at a frequency of 1/20 and are inserted into the 600k period long sequence of mean-zero "raw" shocks described above. We then simulate the model over each of the 300 period blocks, discard any blocks that generate explosive behavior, find blocks that achieve the highest ELB frequency and generate a shock series of at least 60k periods, and save the shock series in the data file <code>trim1=high_phipi.mat</code>.

<li> Trim 2: $\phi_\pi$ is set to 1.5. The shock series from the first trim, <code>trim1=high_phipi.mat</code>, is loaded and the model is simulated over the series. Again, 300 period blocks are analyzed and discarded if they generate explosive behavior. The results of this stage is stored in <code>results_trim.mat</code> and the shock series is stored in <code>trim2=low_phipi.mat</code>. 

<li> Trim 3: $\phi_\pi$ is set to 4. The shock series from the second trim, <code>trim2=low_phipi.mat</code>, is loaded and the signs of each period's shocks are reversed. As in the previous trimming steps, the model is simulated and blocks that generate explosive behavior are discarded. The results of this stage are saved in <code>results_trim_reverse.mat</code>.

Lastly, <code> X_vec_finalize.m </code> reads in the results of Trim 3. Then, a sufficiently high ZLB threshold is found under the requirement that the length of either trimmed series is at least 30k periods long. A secondary trimming scheme that identifies and keeps 300 period blocks at and above the adaptive ZLB threshold is run. Finally, we invert the sign of the final set of trimmed shocks, ensuring that the final shock series produced, <code>shock_series_combined_custom.mat</code> consists of a 60k period sequence of mean-zero shocks.

#### C. Trimming Scheme (shock_series_noCovidGR)

To generate a similar shock series to that used to create Figure A6 in the appendix, <code>shock_series_nocovidGR.mat</code>, the same trimming scheme is used as in section B. The only change required is to set <code>generate_noCovidGR=false</code>, bypassing the step where COVID and Great Recession shocks are inserted into the initial, or "raw," shock series. The final shock series should be stored in <code>shock_series_noCovidGR_custom.mat</code>.

#### D. Generating TFP/Markup only shock series (shock_series_combined_hk_5_{TFP/MK}_only)
To generate a similar shock series to that used to create Figures A8 and A9 in the appendix, we set to 0 all other shocks sequences except the productivity shock sequence in the shock series <code>shock_series_combined_hk_5.mat</code>. Similarly, we set to zero all other shocks sequences except the price mark-up shock. These shock series are stored in the <code> auxfiles </code> folder.
