
util     = @(c)  (c.^(1-param.sigma))./(1-param.sigma);
mutil    = @(c)  (1./(c.^param.sigma));
invutil  = @(u)  (((1-param.sigma).*u).^(1/(1-param.sigma)));
invmutil = @(mu) ((1./mu).^(1/param.sigma));

NN   = grid.nb*grid.na*grid.nse;

VALUE_ind   = 1:NN;
mutil_c_ind = NN + (1:NN);
Va_ind      = 2*NN + (1:NN);

R_cb_ind        = 1;
w_ind           = 2;
A_b_ind         = 3;
B_b_ind         = 4;
A_g_ind         = 5;
Q_ind           = 6;
lev_ind         = 7;
NW_b_ind        = 8;
R_tilde_ind     = 9;
x_cb_ind        = 10;
pastpi_ind      = 11;
pastY_ind       = 12;
pastC_ind       = 13;
pastI_ind       = 14;
pastPROFIT_ind  = 15;
pastunemp_ind   = 16;
pastG_ind       = 17;
pastLT_ind      = 18;
R_star_ind      = 19;
B_F_ind         = 20;
Z_ind           = 21;
PSI_RP_ind      = 22;
eta_ind         = 23;
D_ind           = 24;
GG_ind          = 25;
iota_ind        = 26;
BB_ind          = 27;
PSI_W_ind       = 28;
MP_ind          = 29;
p_mark_ind      = 30;
pgap_ind        = 31;
ygap_ind        = 32;
eps_QE_ind      = 33;
eps_RP_ind      = 34;
eps_B_F_ind     = 35;
eps_BB_ind      = 36;
eps_Z_ind       = 37;
eps_G_ind       = 38;
eps_D_ind       = 39;
eps_R_ind       = 40;
eps_iota_ind    = 41;
eps_eta_ind     = 42;
eps_w_ind       = 43;

idx.R_cb_ind        = R_cb_ind        ;
idx.w_ind           = w_ind           ;
idx.A_b_ind         = A_b_ind         ;
idx.B_b_ind         = B_b_ind         ;
idx.A_g_ind         = A_g_ind         ;
idx.Q_ind           = Q_ind           ;
idx.lev_ind         = lev_ind         ;
idx.NW_b_ind        = NW_b_ind        ;
idx.R_tilde_ind     = R_tilde_ind     ;
idx.x_cb_ind        = x_cb_ind        ;
idx.pastpi_ind      = pastpi_ind      ;
idx.pastY_ind       = pastY_ind       ;
idx.pastC_ind       = pastC_ind       ;
idx.pastI_ind       = pastI_ind       ;
idx.pastPROFIT_ind  = pastPROFIT_ind  ;
idx.pastunemp_ind   = pastunemp_ind   ;
idx.pastG_ind       = pastG_ind       ;
idx.pastLT_ind      = pastLT_ind      ;
idx.R_star_ind      = R_star_ind      ;
idx.B_F_ind         = B_F_ind         ;
idx.Z_ind           = Z_ind           ;
idx.PSI_RP_ind      = PSI_RP_ind      ;
idx.eta_ind         = eta_ind         ;
idx.D_ind           = D_ind           ;
idx.GG_ind          = GG_ind          ;
idx.iota_ind        = iota_ind        ;
idx.BB_ind          = BB_ind          ;
idx.PSI_W_ind       = PSI_W_ind       ;
idx.MP_ind          = MP_ind          ;
idx.p_mark_ind      = p_mark_ind      ;
idx.pgap_ind        = pgap_ind        ;
idx.ygap_ind        = ygap_ind        ;
idx.eps_QE_ind      = eps_QE_ind      ;
idx.eps_B_F_ind     = eps_B_F_ind     ;
idx.eps_RP_ind      = eps_RP_ind      ;
idx.eps_BB_ind      = eps_BB_ind      ;
idx.eps_Z_ind       = eps_Z_ind       ;
idx.eps_G_ind       = eps_G_ind       ;
idx.eps_D_ind       = eps_D_ind       ;
idx.eps_R_ind       = eps_R_ind       ;
idx.eps_iota_ind    = eps_iota_ind    ;
idx.eps_eta_ind     = eps_eta_ind     ;
idx.eps_w_ind       = eps_w_ind       ;


Profit_aux_ind       = 1; % 1
GiniW_ind            = Profit_aux_ind + 1; % 2
GiniI_1_ind          = GiniW_ind      + 1; % 3
GiniI_2_ind          = GiniI_1_ind    + 1; % 4
GiniC_ind            = GiniI_2_ind    + 1; % 5
w_01_ind             = GiniC_ind      + 1; % 6
w_1_ind              = w_01_ind       + 1; % 7
w_10_ind             = w_1_ind        + 1; % 8
w_Q1_ind             = w_10_ind       + 1; % 9
w_Q2_ind             = w_Q1_ind       + 1; % 10
w_Q3_ind             = w_Q2_ind       + 1; % 11
w_Q4_ind             = w_Q3_ind       + 1; % 12
w_Q5_ind             = w_Q4_ind       + 1; % 13
w_90_ind             = w_Q5_ind       + 1; % 14
w_99_ind             = w_90_ind       + 1; % 15
w_999_ind            = w_99_ind       + 1; % 16
I_1_01_ind           = w_999_ind      + 1; % 17
I_1_1_ind            = I_1_01_ind     + 1; % 18
I_1_10_ind           = I_1_1_ind      + 1; % 19
I_1_Q1_ind           = I_1_10_ind     + 1; % 20
I_1_Q2_ind           = I_1_Q1_ind     + 1; % 21
I_1_Q3_ind           = I_1_Q2_ind     + 1; % 22
I_1_Q4_ind           = I_1_Q3_ind     + 1; % 23
I_1_Q5_ind           = I_1_Q4_ind     + 1; % 24
I_1_90_ind           = I_1_Q5_ind     + 1; % 25
I_1_99_ind           = I_1_90_ind     + 1; % 26
I_1_999_ind          = I_1_99_ind     + 1; % 27
I_2_01_ind           = I_1_999_ind    + 1; % 28
I_2_1_ind            = I_2_01_ind     + 1; % 29
I_2_10_ind           = I_2_1_ind      + 1; % 30
I_2_Q1_ind           = I_2_10_ind     + 1; % 31
I_2_Q2_ind           = I_2_Q1_ind     + 1; % 32
I_2_Q3_ind           = I_2_Q2_ind     + 1; % 33
I_2_Q4_ind           = I_2_Q3_ind     + 1; % 34
I_2_Q5_ind           = I_2_Q4_ind     + 1; % 35
I_2_90_ind           = I_2_Q5_ind     + 1; % 36
I_2_99_ind           = I_2_90_ind     + 1; % 37
I_2_999_ind          = I_2_99_ind     + 1; % 38
C_01_ind             = I_2_999_ind    + 1; % 39
C_1_ind              = C_01_ind       + 1; % 40
C_10_ind             = C_1_ind        + 1; % 41
C_Q1_ind             = C_10_ind       + 1; % 42
C_Q2_ind             = C_Q1_ind       + 1; % 43
C_Q3_ind             = C_Q2_ind       + 1; % 44
C_Q4_ind             = C_Q3_ind       + 1; % 45
C_Q5_ind             = C_Q4_ind       + 1; % 46
C_90_ind             = C_Q5_ind       + 1; % 47
C_99_ind             = C_90_ind       + 1; % 48
C_999_ind            = C_99_ind       + 1; % 49
w_I_01_ind           = C_999_ind     + 1; % 50
w_I_1_ind            = w_I_01_ind    + 1; % 51
w_I_10_ind           = w_I_1_ind     + 1; % 52
w_I_Q1_ind           = w_I_10_ind    + 1; % 53
w_I_Q2_ind           = w_I_Q1_ind    + 1; % 54
w_I_Q3_ind           = w_I_Q2_ind    + 1; % 55
w_I_Q4_ind           = w_I_Q3_ind    + 1; % 56
w_I_Q5_ind           = w_I_Q4_ind    + 1; % 57
w_I_90_ind           = w_I_Q5_ind    + 1; % 58
w_I_99_ind           = w_I_90_ind    + 1; % 59
w_I_999_ind          = w_I_99_ind    + 1; % 60
I_I_1_01_ind         = w_I_999_ind      + 1; % 61
I_I_1_1_ind          = I_I_1_01_ind       + 1; % 62
I_I_1_10_ind         = I_I_1_1_ind        + 1; % 63
I_I_1_Q1_ind         = I_I_1_10_ind       + 1; % 64
I_I_1_Q2_ind         = I_I_1_Q1_ind       + 1; % 65
I_I_1_Q3_ind         = I_I_1_Q2_ind       + 1; % 66
I_I_1_Q4_ind         = I_I_1_Q3_ind       + 1; % 67
I_I_1_Q5_ind         = I_I_1_Q4_ind       + 1; % 68
I_I_1_90_ind         = I_I_1_Q5_ind       + 1; % 69
I_I_1_99_ind         = I_I_1_90_ind       + 1; % 70
I_I_1_999_ind        = I_I_1_99_ind       + 1; % 71
I_I_2_01_ind         = I_I_1_999_ind    + 1; % 72
I_I_2_1_ind          = I_I_2_01_ind     + 1; % 73
I_I_2_10_ind         = I_I_2_1_ind      + 1; % 74
I_I_2_Q1_ind         = I_I_2_10_ind     + 1; % 75
I_I_2_Q2_ind         = I_I_2_Q1_ind     + 1; % 76
I_I_2_Q3_ind         = I_I_2_Q2_ind     + 1; % 77
I_I_2_Q4_ind         = I_I_2_Q3_ind     + 1; % 78
I_I_2_Q5_ind         = I_I_2_Q4_ind     + 1; % 79
I_I_2_90_ind         = I_I_2_Q5_ind     + 1; % 80
I_I_2_99_ind         = I_I_2_90_ind     + 1; % 81
I_I_2_999_ind        = I_I_2_99_ind     + 1; % 82
C_I_01_ind           = I_I_2_999_ind    + 1; % 83
C_I_1_ind            = C_I_01_ind       + 1; % 84
C_I_10_ind           = C_I_1_ind        + 1; % 85
C_I_Q1_ind           = C_I_10_ind       + 1; % 86
C_I_Q2_ind           = C_I_Q1_ind       + 1; % 87
C_I_Q3_ind           = C_I_Q2_ind       + 1; % 88
C_I_Q4_ind           = C_I_Q3_ind       + 1; % 89
C_I_Q5_ind           = C_I_Q4_ind       + 1; % 90
C_I_90_ind           = C_I_Q5_ind       + 1; % 91
C_I_99_ind           = C_I_90_ind       + 1; % 92
C_I_999_ind          = C_I_99_ind       + 1; % 93
I_90to10_ind         = C_I_999_ind    + 1; % 94
I_50to10_ind         = I_90to10_ind   + 1; % 95
I_90to50_ind         = I_50to10_ind   + 1; % 96
W_90to50_ind         = I_90to50_ind       + 1; % 97   %Differentiation between I/W and Inc/Wlth being between threshold vals (income50/w50 vs avg income_P90/B_10)
Inc_1_T10toB10_ind   = W_90to50_ind       + 1; % 98
Inc_1_T10toQ3_ind    = Inc_1_T10toB10_ind + 1; % 99
Inc_1_Q3toB10_ind    = Inc_1_T10toQ3_ind  + 1; % 100
Inc_2_T10toB10_ind   = Inc_1_Q3toB10_ind  + 1; % 101
Inc_2_T10toQ3_ind    = Inc_2_T10toB10_ind + 1; % 102
Inc_2_Q3toB10_ind    = Inc_2_T10toQ3_ind  + 1; % 103
Wlth_T10toQ3_ind     = Inc_2_Q3toB10_ind  + 1; % 104
C_T10toB10_ind       = Wlth_T10toQ3_ind   + 1; % 105
C_T10toQ3_ind        = C_T10toB10_ind     + 1; % 106
C_Q3toB10_ind        = C_T10toQ3_ind      + 1; % 107
Inc_I_1_T10toB10_ind = C_Q3toB10_ind        + 1; % 108
Inc_I_1_T10toQ3_ind  = Inc_I_1_T10toB10_ind + 1; % 109
Inc_I_1_Q3toB10_ind  = Inc_I_1_T10toQ3_ind  + 1; % 110
Inc_I_2_T10toB10_ind = Inc_I_1_Q3toB10_ind  + 1; % 111
Inc_I_2_T10toQ3_ind  = Inc_I_2_T10toB10_ind + 1; % 112
Inc_I_2_Q3toB10_ind  = Inc_I_2_T10toQ3_ind  + 1; % 113
Wlth_I_T10toQ3_ind   = Inc_I_2_Q3toB10_ind  + 1; % 114
C_I_T10toB10_ind     = Wlth_I_T10toQ3_ind   + 1; % 115
C_I_T10toQ3_ind      = C_I_T10toB10_ind     + 1; % 116
C_I_Q3toB10_ind      = C_I_T10toQ3_ind      + 1; % 117


MRS_ind        = C_I_Q3toB10_ind    + 1;
A_hh_ind       = MRS_ind       + 1;
B_hh_ind       = A_hh_ind      + 1;
C_ind          = B_hh_ind      + 1;
N_ind          = C_ind         + 1;
L_ind          = N_ind         + 1;
UB_ind         = L_ind         + 1;
K_ind          = UB_ind        + 1;
B_ind          = K_ind         + 1;
B_gov_ncp_ind  = B_ind         + 1;
T_ind          = B_gov_ncp_ind + 1;
LT_ind 	       = T_ind         + 1;
G_ind          = LT_ind 	   + 1;
Lambda_ind     = G_ind         + 1;
pi_ind         = Lambda_ind    + 1;
V_ind          = pi_ind        + 1;
J_ind          = V_ind + (1:grid.ns)';  
h_ind          = J_ind(end)    + 1;          
v_ind          = h_ind         + 1;
Y_ind          = v_ind         + 1;
Profit_ind     = Y_ind         + 1;
r_k_ind        = Profit_ind    + 1;
r_a_ind        = r_k_ind       + 1;
MC_ind         = r_a_ind       + 1;
unemp_ind      = MC_ind        + 1;
nn_ind         = unemp_ind     + 1;
M_ind          = nn_ind        + 1;
f_ind          = M_ind         + 1;
zz_ind         = f_ind         + 1;
xx_ind         = zz_ind        + 1;
vv_ind         = xx_ind        + 1;
ee_ind         = vv_ind        + 1;
C_b_ind        = ee_ind        + 1;
Profit_FI_ind  = C_b_ind       + 1;
RRa_ind        = Profit_FI_ind + 1;
RR_ind         = RRa_ind       + 1;
I_ind          = RR_ind        + 1;
x_k_ind        = I_ind         + 1;
A_g_obs_ind    = x_k_ind       + 1;
Y_obs_ind      = A_g_obs_ind    + 1; % 6
C_obs_ind      = Y_obs_ind      + 1; % 5
I_obs_ind      = C_obs_ind      + 1; % 4
w_obs_ind      = I_obs_ind      + 1; % 3
PROFIT_obs_ind = w_obs_ind      + 1; % 2
unemp_obs_ind  = PROFIT_obs_ind + 1; % 1
inf_obs_ind    = unemp_obs_ind  + 1;
R_obs_ind      = inf_obs_ind    + 1;
pastw_ind      = R_obs_ind      + 1;
G_obs_ind      = pastw_ind      + 1;

pastYY_ind        = G_obs_ind       + 1;
pastCC_ind        = pastYY_ind      + 1; 
pastII_ind        = pastCC_ind      + 1; 
pastPPROFIT_ind   = pastII_ind      + 1;
pastuu_ind        = pastPPROFIT_ind + 1;
pastGG_ind        = pastuu_ind      + 1;
pastA_g_ind       = pastGG_ind      + 1;

l_lambda_ind      = pastA_g_ind    + 1;
pastQ_ind         = l_lambda_ind   + 1;
x_I_ind           = pastQ_ind      + 1;
eta2_ind          = x_I_ind        + 1;
iota2_ind         = eta2_ind       + 1;
pastLT2_ind       = iota2_ind      + 1;
pastG2_ind        = pastLT2_ind     + 1;
LT_obs_ind        = pastG2_ind      + 1;
B_gov_ncp2_ind    = LT_obs_ind      + 1;

w2_ind            = B_gov_ncp2_ind  + 1;
Profit2_ind       = w2_ind          + 1;
Profit3_ind       = Profit2_ind     + 1;
Profit_FI2_ind    = Profit3_ind     + 1;
r_a2_ind          = Profit_FI2_ind  + 1;


idx.Profit_aux_ind = Profit_aux_ind;
idx.GiniW_ind = GiniW_ind;
idx.GiniI_1_ind = GiniI_1_ind;
idx.GiniI_2_ind = GiniI_2_ind;
idx.GiniC_ind = GiniC_ind;
idx.w_01_ind = w_01_ind;
idx.w_1_ind = w_1_ind;
idx.w_10_ind = w_10_ind;
idx.w_Q1_ind = w_Q1_ind;
idx.w_Q2_ind = w_Q2_ind;
idx.w_Q3_ind = w_Q3_ind;
idx.w_Q4_ind = w_Q4_ind;
idx.w_Q5_ind = w_Q5_ind;
idx.w_90_ind = w_90_ind;
idx.w_99_ind = w_99_ind;
idx.w_999_ind = w_999_ind;
idx.I_1_01_ind = I_1_01_ind;
idx.I_1_1_ind = I_1_1_ind;
idx.I_1_10_ind = I_1_10_ind;
idx.I_1_Q1_ind = I_1_Q1_ind;
idx.I_1_Q2_ind = I_1_Q2_ind;
idx.I_1_Q3_ind = I_1_Q3_ind;
idx.I_1_Q4_ind = I_1_Q4_ind;
idx.I_1_Q5_ind = I_1_Q5_ind;
idx.I_1_90_ind = I_1_90_ind;
idx.I_1_99_ind = I_1_99_ind;
idx.I_1_999_ind = I_1_999_ind;
idx.I_2_01_ind = I_2_01_ind;
idx.I_2_1_ind = I_2_1_ind;
idx.I_2_10_ind = I_2_10_ind;
idx.I_2_Q1_ind = I_2_Q1_ind;
idx.I_2_Q2_ind = I_2_Q2_ind;
idx.I_2_Q3_ind = I_2_Q3_ind;
idx.I_2_Q4_ind = I_2_Q4_ind;
idx.I_2_Q5_ind = I_2_Q5_ind;
idx.I_2_90_ind = I_2_90_ind;
idx.I_2_99_ind = I_2_99_ind;
idx.I_2_999_ind = I_2_999_ind;
idx.C_01_ind = C_01_ind;
idx.C_1_ind = C_1_ind;
idx.C_10_ind = C_10_ind;
idx.C_Q1_ind = C_Q1_ind;
idx.C_Q2_ind = C_Q2_ind;
idx.C_Q3_ind = C_Q3_ind;
idx.C_Q4_ind = C_Q4_ind;
idx.C_Q5_ind = C_Q5_ind;
idx.C_90_ind = C_90_ind;
idx.C_99_ind = C_99_ind;
idx.C_999_ind = C_999_ind;
idx.w_I_01_ind = w_I_01_ind;
idx.w_I_1_ind = w_I_1_ind;
idx.w_I_10_ind = w_I_10_ind;
idx.w_I_Q1_ind = w_I_Q1_ind;
idx.w_I_Q2_ind = w_I_Q2_ind;
idx.w_I_Q3_ind = w_I_Q3_ind;
idx.w_I_Q4_ind = w_I_Q4_ind;
idx.w_I_Q5_ind = w_I_Q5_ind;
idx.w_I_90_ind = w_I_90_ind;
idx.w_I_99_ind = w_I_99_ind;
idx.w_I_999_ind = w_I_999_ind;
idx.I_I_1_01_ind = I_I_1_01_ind;
idx.I_I_1_1_ind = I_I_1_1_ind;
idx.I_I_1_10_ind = I_I_1_10_ind;
idx.I_I_1_Q1_ind = I_I_1_Q1_ind;
idx.I_I_1_Q2_ind = I_I_1_Q2_ind;
idx.I_I_1_Q3_ind = I_I_1_Q3_ind;
idx.I_I_1_Q4_ind = I_I_1_Q4_ind;
idx.I_I_1_Q5_ind = I_I_1_Q5_ind;
idx.I_I_1_90_ind = I_I_1_90_ind;
idx.I_I_1_99_ind = I_I_1_99_ind;
idx.I_I_1_999_ind = I_I_1_999_ind;
idx.I_I_2_01_ind = I_I_2_01_ind;
idx.I_I_2_1_ind = I_I_2_1_ind;
idx.I_I_2_10_ind = I_I_2_10_ind;
idx.I_I_2_Q1_ind = I_I_2_Q1_ind;
idx.I_I_2_Q2_ind = I_I_2_Q2_ind;
idx.I_I_2_Q3_ind = I_I_2_Q3_ind;
idx.I_I_2_Q4_ind = I_I_2_Q4_ind;
idx.I_I_2_Q5_ind = I_I_2_Q5_ind;
idx.I_I_2_90_ind = I_I_2_90_ind;
idx.I_I_2_99_ind = I_I_2_99_ind;
idx.I_I_2_999_ind = I_I_2_999_ind;
idx.C_I_01_ind = C_I_01_ind;
idx.C_I_1_ind = C_I_1_ind;
idx.C_I_10_ind = C_I_10_ind;
idx.C_I_Q1_ind = C_I_Q1_ind;
idx.C_I_Q2_ind = C_I_Q2_ind;
idx.C_I_Q3_ind = C_I_Q3_ind;
idx.C_I_Q4_ind = C_I_Q4_ind;
idx.C_I_Q5_ind = C_I_Q5_ind;
idx.C_I_90_ind = C_I_90_ind;
idx.C_I_99_ind = C_I_99_ind;
idx.C_I_999_ind = C_I_999_ind;
idx.I_90to10_ind = I_90to10_ind;
idx.I_50to10_ind = I_50to10_ind;
idx.I_90to50_ind = I_90to50_ind;
idx.W_90to50_ind = W_90to50_ind;
idx.Inc_1_T10toB10_ind = Inc_1_T10toB10_ind;
idx.Inc_1_T10toQ3_ind = Inc_1_T10toQ3_ind;
idx.Inc_1_Q3toB10_ind = Inc_1_Q3toB10_ind;
idx.Inc_2_T10toB10_ind = Inc_2_T10toB10_ind;
idx.Inc_2_T10toQ3_ind = Inc_2_T10toQ3_ind;
idx.Inc_2_Q3toB10_ind = Inc_2_Q3toB10_ind;
idx.Wlth_T10toQ3_ind = Wlth_T10toQ3_ind;
idx.C_T10toB10_ind = C_T10toB10_ind;
idx.C_T10toQ3_ind = C_T10toQ3_ind;
idx.C_Q3toB10_ind = C_Q3toB10_ind;
idx.Inc_I_1_T10toB10_ind = Inc_I_1_T10toB10_ind;
idx.Inc_I_1_T10toQ3_ind = Inc_I_1_T10toQ3_ind;
idx.Inc_I_1_Q3toB10_ind = Inc_I_1_Q3toB10_ind;
idx.Inc_I_2_T10toB10_ind = Inc_I_2_T10toB10_ind;
idx.Inc_I_2_T10toQ3_ind = Inc_I_2_T10toQ3_ind;
idx.Inc_I_2_Q3toB10_ind = Inc_I_2_Q3toB10_ind;
idx.Wlth_I_T10toQ3_ind = Wlth_I_T10toQ3_ind;
idx.C_I_T10toB10_ind = C_I_T10toB10_ind;
idx.C_I_T10toQ3_ind = C_I_T10toQ3_ind;
idx.C_I_Q3toB10_ind = C_I_Q3toB10_ind;


idx.MRS_ind         = MRS_ind;
idx.A_hh_ind        = A_hh_ind;
idx.B_hh_ind        = B_hh_ind;
idx.C_ind           = C_ind;
idx.N_ind           = N_ind;
idx.L_ind           = L_ind;
idx.UB_ind          = UB_ind;
idx.K_ind           = K_ind;
idx.B_ind           = B_ind;
idx.B_gov_ncp_ind   = B_gov_ncp_ind;
idx.T_ind           = T_ind;
idx.LT_ind          = LT_ind;
idx.G_ind           = G_ind;
idx.Lambda_ind      = Lambda_ind;
idx.pi_ind          = pi_ind;
idx.V_ind           = V_ind;
idx.J_ind           = J_ind;
idx.h_ind           = h_ind;
idx.v_ind           = v_ind;
idx.Y_ind           = Y_ind;
idx.Profit_ind      = Profit_ind;
idx.r_k_ind         = r_k_ind;
idx.r_a_ind         = r_a_ind;
idx.MC_ind          = MC_ind;
idx.unemp_ind       = unemp_ind;
idx.nn_ind          = nn_ind;
idx.M_ind           = M_ind;
idx.f_ind           = f_ind;
idx.zz_ind          = zz_ind;
idx.xx_ind          = xx_ind;
idx.vv_ind          = vv_ind;
idx.ee_ind          = ee_ind;
idx.C_b_ind         = C_b_ind;
idx.Profit_FI_ind   = Profit_FI_ind;
idx.RRa_ind         = RRa_ind;
idx.RR_ind          = RR_ind;
idx.I_ind           = I_ind;
idx.x_k_ind         = x_k_ind;
idx.A_g_obs_ind     = A_g_obs_ind;
idx.Y_obs_ind       = Y_obs_ind;
idx.C_obs_ind       = C_obs_ind;
idx.I_obs_ind       = I_obs_ind;
idx.w_obs_ind       = w_obs_ind;
idx.PROFIT_obs_ind  = PROFIT_obs_ind;
idx.unemp_obs_ind   = unemp_obs_ind;
idx.inf_obs_ind     = inf_obs_ind;
idx.R_obs_ind       = R_obs_ind;
idx.pastw_ind       = pastw_ind;
idx.G_obs_ind       = G_obs_ind;
idx.pastYY_ind      = pastYY_ind;
idx.pastCC_ind      = pastCC_ind;
idx.pastII_ind      = pastII_ind;
idx.pastPPROFIT_ind = pastPPROFIT_ind;
idx.pastuu_ind      = pastuu_ind;
idx.pastGG_ind      = pastGG_ind;
idx.pastA_g_ind     = pastA_g_ind;
idx.l_lambda_ind    = l_lambda_ind;
idx.pastQ_ind       = pastQ_ind;
idx.x_I_ind         = x_I_ind; 
idx.eta2_ind        = eta2_ind; 
idx.iota2_ind       = iota2_ind; 
idx.pastLT2_ind     = pastLT2_ind; 
idx.pastG2_ind      = pastG2_ind;
idx.LT_obs_ind      = LT_obs_ind;
idx.B_gov_ncp2_ind  = B_gov_ncp2_ind;

idx.w2_ind          = w2_ind;
idx.Profit2_ind     = Profit2_ind;
idx.Profit3_ind     = Profit3_ind;
idx.Profit_FI2_ind  = Profit_FI2_ind;
idx.r_a2_ind        = r_a2_ind;
