function out = prior_density_covid_v10(est_param_set,prior_info)

prior.kappa     = est_param_set(1 );
prior.rho_w     = est_param_set(2 );
prior.d         = est_param_set(3 );
prior.phi       = est_param_set(4 );
prior.phi_pi    = est_param_set(5 );
prior.phi_u     = est_param_set(6 );
prior.rho_BB    = est_param_set(7 );
prior.rho_B     = est_param_set(8 );
prior.rho_D     = est_param_set(9 );
prior.rho_G     = est_param_set(10);
prior.rho_R     = est_param_set(11);
prior.rho_Z     = est_param_set(12);
prior.rho_eta   = est_param_set(13);
prior.rho_iota  = est_param_set(14);
prior.sig_D     = est_param_set(15)/100 ;
prior.sig_G     = est_param_set(16)/100 ;
prior.sig_R     = est_param_set(17)/100 ;
prior.sig_Z     = est_param_set(18)/100 ;
prior.sig_eta   = est_param_set(19)/100 ;
prior.sig_iota  = est_param_set(20)/100 ;
prior.sig_w     = est_param_set(21)/100 ;
prior.sig_BB    = est_param_set(22)/100 ;
prior.GAMMA     = est_param_set(23);
prior.sig_B_F   = est_param_set(24)/100;
prior.rho_B_F   = est_param_set(25);
prior.iota      = est_param_set(26);
out_aux = zeros(26,1);

out_aux(1   ) = gamma_pdf    (prior.kappa         , prior_info(1 ,1)  , prior_info(1 ,2));
out_aux(2   ) = beta_pdf     (prior.rho_w         , prior_info(2 ,1)  , prior_info(2 ,2));
out_aux(3   ) = beta_pdf     (prior.d             , prior_info(3 ,1)  , prior_info(3 ,2));
out_aux(4   ) = normpdf      (prior.phi           , prior_info(4 ,1)  , prior_info(4 ,2));
out_aux(5   ) = normpdf      (prior.phi_pi        , prior_info(5 ,1)  , prior_info(5 ,2));
out_aux(6   ) = normpdf      (prior.phi_u         , prior_info(6 ,1)  , prior_info(6 ,2));
out_aux(7   ) = beta_pdf     (prior.rho_BB        , prior_info(7 ,1)  , prior_info(7 ,2));
out_aux(8   ) = beta_pdf     (prior.rho_B         , prior_info(8 ,1)  , prior_info(8 ,2));
out_aux(9   ) = beta_pdf     (prior.rho_D         , prior_info(9, 1)  , prior_info(9 ,2));
out_aux(10  ) = beta_pdf     (prior.rho_G         , prior_info(10,1)  , prior_info(10,2));
out_aux(11  ) = beta_pdf     (prior.rho_R         , prior_info(11,1)  , prior_info(11,2));
out_aux(12  ) = beta_pdf     (prior.rho_Z         , prior_info(12,1)  , prior_info(12,2));
out_aux(13  ) = beta_pdf     (prior.rho_eta       , prior_info(13,1)  , prior_info(13,2));
out_aux(14  ) = beta_pdf     (prior.rho_iota      , prior_info(14,1)  , prior_info(14,2));
out_aux(15  ) = inv_gamma_pdf(prior.sig_D         , prior_info(15,1)  , prior_info(15,2));
out_aux(16  ) = inv_gamma_pdf(prior.sig_G         , prior_info(16,1)  , prior_info(16,2));
out_aux(17  ) = inv_gamma_pdf(prior.sig_R         , prior_info(17,1)  , prior_info(17,2));
out_aux(18  ) = inv_gamma_pdf(prior.sig_Z         , prior_info(18,1)  , prior_info(18,2));
out_aux(19  ) = inv_gamma_pdf(prior.sig_eta       , prior_info(19,1)  , prior_info(19,2));
out_aux(20  ) = inv_gamma_pdf(prior.sig_iota      , prior_info(20,1)  , prior_info(20,2));
out_aux(21  ) = inv_gamma_pdf(prior.sig_w         , prior_info(21,1)  , prior_info(21,2));
out_aux(22  ) = inv_gamma_pdf(prior.sig_BB        , prior_info(22,1)  , prior_info(22,2));
out_aux(23  ) = beta_pdf     (prior.GAMMA         , prior_info(23,1)  , prior_info(23,2));
out_aux(24  ) = inv_gamma_pdf(prior.sig_B_F       , prior_info(24,1)  , prior_info(24,2));
out_aux(25  ) = beta_pdf     (prior.rho_B_F       , prior_info(25,1)  , prior_info(25,2));
out_aux(26  ) = gamma_pdf    (prior.iota          , prior_info(26,1)  , prior_info(26,2));


out = -log(prod(out_aux));