function out = q_cons2(c_a_guess,c_n_guess,W_fc,nn,AProb,mu_dist,meshes,param,grid,tau_w)

out = (sum(sum(sum((c_a_guess(:,:,1:grid.ns)+(1-tau_w)/(1+param.xi)*W_fc*meshes.se(:,:,1:grid.ns).*nn).*  AProb(:,:,1:grid.ns)  .*mu_dist(:,:,1:grid.ns)))) ...
	            + sum(sum(sum((c_n_guess(:,:,1:grid.ns)+(1-tau_w)/(1+param.xi)*W_fc*meshes.se(:,:,1:grid.ns).*nn).*(1-AProb(:,:,1:grid.ns)).*mu_dist(:,:,1:grid.ns)))) ...
               	+ sum(sum(sum(c_a_guess(:,:,grid.ns+1:end).*   AProb(:,:,grid.ns+1:end) .*mu_dist(:,:,grid.ns+1:end)))) ...
               	+ sum(sum(sum(c_n_guess(:,:,grid.ns+1:end).*(1-AProb(:,:,grid.ns+1:end)).*mu_dist(:,:,grid.ns+1:end))))) ... 
	             /sum(sum(sum(mu_dist))); 

end