invutil  = @(u)  (((1-param.sigma).*u).^(1/(1-param.sigma)));
invmutil = @(mu) ((1./mu).^(1/param.sigma));

% State variables: distribution, R, pi, w, inven + three exogenous shocks (MP, Z, and discount factor shock)


switch(param.adjust)
	case('G')
		Xss = [...
			   squeeze(sum(sum(mu_dist,2),3));  ... % marginal distribution over bond
			   squeeze(sum(sum(mu_dist,1),3))'; ... % marginal distribution over equity
			   squeeze(sum(sum(mu_dist,2),1));  ... % marginal distribution over idiosyncratic productivity ane employment status
			   log(param.R_cb); log(param.w_bar); ...
			   log(SS_stats.A_b); log(SS_stats.B_b); log(SS_stats.A_g); ...
			   log(param.q); log(SS_stats.leverage); log(SS_stats.NW_b); log(param.R_cb); 0; ...
			   log(param.pi_bar); ...
			   log(SS_stats.Y); log(SS_stats.Chh); log(SS_stats.I2); log(SS_stats.Profit+SS_stats.Profit_FI); log(param.u); log(param.w_bar); log(SS_stats.LT); log(param.R_cb); log(SS_stats.Y/(SS_stats.Y-SS_stats.B_F)); ...
			   log(1); log(1); log(param.eta); log(1); log(SS_stats.Y/(SS_stats.Y-SS_stats.LT-SS_stats.C_b)); log(1); log(1); log(1); log(1); log(param.eta/(param.eta-1)); ...
			   log(1); log(1); ...
			   0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];	     

	case('LT')
		Xss = [ ...
			   squeeze(sum(sum(mu_dist,2),3));  ... % marginal distribution over bond
			   squeeze(sum(sum(mu_dist,1),3))'; ... % marginal distribution over equity
			   squeeze(sum(sum(mu_dist,2),1));  ... % marginal distribution over idiosyncratic productivity ane employment status
			   log(param.R_cb); log(param.w_bar); ...
			   log(SS_stats.A_b); log(SS_stats.B_b); log(SS_stats.A_g); ...
			   log(param.q); log(SS_stats.leverage); log(SS_stats.NW_b); log(param.R_cb); 0; ...
			   log(param.pi_bar); ...
			   log(SS_stats.Y); log(SS_stats.Chh); log(SS_stats.I2); log(SS_stats.Profit+SS_stats.Profit_FI); log(param.u); log(SS_stats.G); log(SS_stats.LT); log(param.R_cb); log(SS_stats.Y/(SS_stats.Y-SS_stats.B_F)); ...
			   log(1); log(1); log(param.eta); log(1); log(SS_stats.Y/(SS_stats.Y-SS_stats.G)); log(1); log(1); log(1); log(1); log(param.eta/(param.eta-1)); ...
			   log(1); log(1); ...
			   0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];	   
end			   
													
switch(param.adjust)
	case('G')													
		Yss = [invutil(Value(:)); invmutil(mutil_c(:)); invmutil(Va(:)); ...
				log(SS_stats.Profit);log(SS_stats.GiniW);log(SS_stats.GiniIncome);log(SS_stats.GiniIncome); log(SS_stats.GiniCons); ...
				log(1+SS_stats.w_B01);log(1+SS_stats.w_B1);log(1+SS_stats.w_B10);log(1+SS_stats.w_Q1);log(SS_stats.w_Q2);log(SS_stats.w_Q3);log(SS_stats.w_Q4);log(SS_stats.w_Q5);log(SS_stats.w_P90);log(SS_stats.w_P99);log(SS_stats.w_P999);...
				log(SS_stats.income_B01);log(SS_stats.income_B1);log(SS_stats.income_B10	);log(SS_stats.income_Q1);log(SS_stats.income_Q2);log(SS_stats.income_Q3);log(SS_stats.income_Q4);log(SS_stats.income_Q5);log(SS_stats.income_P90);log(SS_stats.income_P99);log(SS_stats.income_P999); ...
				log(SS_stats.income_B01);log(SS_stats.income_B1);log(SS_stats.income_B10	);log(SS_stats.income_Q1);log(SS_stats.income_Q2);log(SS_stats.income_Q3);log(SS_stats.income_Q4);log(SS_stats.income_Q5);log(SS_stats.income_P90);log(SS_stats.income_P99);log(SS_stats.income_P999); ...
				log(SS_stats.C_B01);log(SS_stats.C_B1);log(SS_stats.C_B10);log(SS_stats.C_Q1);log(SS_stats.C_Q2);log(SS_stats.C_Q3);log(SS_stats.C_Q4);log(SS_stats.C_Q5);log(SS_stats.C_P90);log(SS_stats.C_P99);log(SS_stats.C_P999); ...
				log(1+SS_stats.w_I_B01);log(1+SS_stats.w_I_B1);log(1+SS_stats.w_I_B10);log(1+SS_stats.w_I_Q1);log(SS_stats.w_I_Q2);log(SS_stats.w_I_Q3);log(SS_stats.w_I_Q4);log(SS_stats.w_I_Q5);log(SS_stats.w_I_P90);log(SS_stats.w_I_P99);log(SS_stats.w_I_P999);...
				log(SS_stats.income_I_B01);log(SS_stats.income_I_B1);log(SS_stats.income_I_B10	);log(SS_stats.income_I_Q1);log(SS_stats.income_I_Q2);log(SS_stats.income_I_Q3);log(SS_stats.income_I_Q4);log(SS_stats.income_I_Q5);log(SS_stats.income_I_P90);log(SS_stats.income_I_P99);log(SS_stats.income_I_P999); ...
				log(SS_stats.income_I_B01);log(SS_stats.income_I_B1);log(SS_stats.income_I_B10	);log(SS_stats.income_I_Q1);log(SS_stats.income_I_Q2);log(SS_stats.income_I_Q3);log(SS_stats.income_I_Q4);log(SS_stats.income_I_Q5);log(SS_stats.income_I_P90);log(SS_stats.income_I_P99);log(SS_stats.income_I_P999); ...
				log(SS_stats.C_I_B01);log(SS_stats.C_I_B1);log(SS_stats.C_I_B10);log(SS_stats.C_I_Q1);log(SS_stats.C_I_Q2);log(SS_stats.C_I_Q3);log(SS_stats.C_I_Q4);log(SS_stats.C_I_Q5);log(SS_stats.C_I_P90);log(SS_stats.C_I_P99);log(SS_stats.C_I_P999); ...
				log(SS_stats.income90/SS_stats.income10) ; log(SS_stats.income50/SS_stats.income10); log(SS_stats.income90/SS_stats.income50) ; log(SS_stats.w90/SS_stats.w50); ...
				log(SS_stats.income_P90/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_Q3); log(SS_stats.income_Q3/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_Q3); log(SS_stats.income_Q3/SS_stats.income_B10); log(SS_stats.w_P90/SS_stats.w_Q3); log(SS_stats.C_P90/SS_stats.C_B10); log(SS_stats.C_P90/SS_stats.C_Q3); log(SS_stats.C_Q3/SS_stats.C_B10); ...
				log(SS_stats.income_I_P90/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_Q3); log(SS_stats.income_I_Q3/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_Q3); log(SS_stats.income_I_Q3/SS_stats.income_I_B10); log(SS_stats.w_I_P90/SS_stats.w_I_Q3); log(SS_stats.C_I_P90/SS_stats.C_I_B10); log(SS_stats.C_I_P90/SS_stats.C_I_Q3); log(SS_stats.C_I_Q3/SS_stats.C_I_B10); ...
				log(SS_stats.MRS)   ; log(SS_stats.A_hh)   ; log(SS_stats.B_nb/(1-param.death_rate)*param.b_a_aux); log(SS_stats.Chh); ...
				log(SS_stats.N)     ; log(SS_stats.L)      ; log(SS_stats.UB)       ; ...
				log(grid.K)         ; log(SS_stats.B2)     ; log(SS_stats.B_gov_ncp); ... 
				log(SS_stats.T)     ; log(SS_stats.LT)     ; log(SS_stats.G)        ;  ...
				log(SS_stats.Lambda); log(param.pi_bar)    ; ...
				log(SS_stats.V)     ; log(SS_stats.J)      ; log(SS_stats.r_l)  ; log(SS_stats.v)   ; ...
				log(SS_stats.Y)     ; log(SS_stats.Profit) ; log(SS_stats.r_k)  ; log(SS_stats.r_a) ; log(SS_stats.mc); ...				
				log(SS_stats.u)     ; log(param.n)         ; log(SS_stats.M)    ; log(SS_stats.f) ; ...
				log(SS_stats.zz)    ; log(SS_stats.xx)     ; log(SS_stats.vv)   ; log(SS_stats.ee); log(SS_stats.C_b); log(SS_stats.Profit_FI);  ...
				log(SS_stats.R_a)   ; log(SS_stats.R)      ; log(SS_stats.I2)   ; ...
				0                   ; ...
				log(SS_stats.A_g); log(SS_stats.Y)  ; log(SS_stats.C); log(SS_stats.I2); log(param.w_bar); log(SS_stats.Profit+SS_stats.Profit_FI); ...
				log(100*param.u)     ; log(param.pi_bar); log(param.R_cb); log(param.w_bar); log(SS_stats.G); ...
				log(SS_stats.Y); log(SS_stats.Chh); log(SS_stats.I2); log(SS_stats.Profit+SS_stats.Profit_FI); log(param.u); log(SS_stats.LT); log(SS_stats.A_g); ...
				log(param.lambda); 0; 0; log(param.eta); 0; log(SS_stats.LT); log(SS_stats.G); log(SS_stats.LT); log(SS_stats.B_gov_ncp2); ...
				log(param.w_bar); log(SS_stats.Profit); log(SS_stats.Profit); log(SS_stats.Profit_FI); log(SS_stats.r_a)];  	
	case('LT')				
													
		Yss = [invutil(Value(:)); invmutil(mutil_c(:)); invmutil(Va(:)); ...
				log(SS_stats.Profit);log(SS_stats.GiniW);log(SS_stats.GiniIncome);log(SS_stats.GiniIncome); log(SS_stats.GiniCons); ...
				log(1+SS_stats.w_B01);log(1+SS_stats.w_B1);log(1+SS_stats.w_B10);log(1+SS_stats.w_Q1);log(SS_stats.w_Q2);log(SS_stats.w_Q3);log(SS_stats.w_Q4);log(SS_stats.w_Q5);log(SS_stats.w_P90);log(SS_stats.w_P99);log(SS_stats.w_P999);...
				log(SS_stats.income_B01);log(SS_stats.income_B1);log(SS_stats.income_B10	);log(SS_stats.income_Q1);log(SS_stats.income_Q2);log(SS_stats.income_Q3);log(SS_stats.income_Q4);log(SS_stats.income_Q5);log(SS_stats.income_P90);log(SS_stats.income_P99);log(SS_stats.income_P999); ...
				log(SS_stats.income_B01);log(SS_stats.income_B1);log(SS_stats.income_B10	);log(SS_stats.income_Q1);log(SS_stats.income_Q2);log(SS_stats.income_Q3);log(SS_stats.income_Q4);log(SS_stats.income_Q5);log(SS_stats.income_P90);log(SS_stats.income_P99);log(SS_stats.income_P999); ...
				log(SS_stats.C_B01);log(SS_stats.C_B1);log(SS_stats.C_B10);log(SS_stats.C_Q1);log(SS_stats.C_Q2);log(SS_stats.C_Q3);log(SS_stats.C_Q4);log(SS_stats.C_Q5);log(SS_stats.C_P90);log(SS_stats.C_P99);log(SS_stats.C_P999); ...
				log(1+SS_stats.w_I_B01);log(1+SS_stats.w_I_B1);log(1+SS_stats.w_I_B10);log(1+SS_stats.w_I_Q1);log(SS_stats.w_I_Q2);log(SS_stats.w_I_Q3);log(SS_stats.w_I_Q4);log(SS_stats.w_I_Q5);log(SS_stats.w_I_P90);log(SS_stats.w_I_P99);log(SS_stats.w_I_P999);...
				log(SS_stats.income_I_B01);log(SS_stats.income_I_B1);log(SS_stats.income_I_B10	);log(SS_stats.income_I_Q1);log(SS_stats.income_I_Q2);log(SS_stats.income_I_Q3);log(SS_stats.income_I_Q4);log(SS_stats.income_I_Q5);log(SS_stats.income_I_P90);log(SS_stats.income_I_P99);log(SS_stats.income_I_P999); ...
				log(SS_stats.income_I_B01);log(SS_stats.income_I_B1);log(SS_stats.income_I_B10	);log(SS_stats.income_I_Q1);log(SS_stats.income_I_Q2);log(SS_stats.income_I_Q3);log(SS_stats.income_I_Q4);log(SS_stats.income_I_Q5);log(SS_stats.income_I_P90);log(SS_stats.income_I_P99);log(SS_stats.income_I_P999); ...
				log(SS_stats.C_I_B01);log(SS_stats.C_I_B1);log(SS_stats.C_I_B10);log(SS_stats.C_I_Q1);log(SS_stats.C_I_Q2);log(SS_stats.C_I_Q3);log(SS_stats.C_I_Q4);log(SS_stats.C_I_Q5);log(SS_stats.C_I_P90);log(SS_stats.C_I_P99);log(SS_stats.C_I_P999); ...
				log(SS_stats.income90/SS_stats.income10) ; log(SS_stats.income50/SS_stats.income10); log(SS_stats.income90/SS_stats.income50) ; log(SS_stats.w90/SS_stats.w50); ...
				log(SS_stats.income_P90/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_Q3); log(SS_stats.income_Q3/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_B10); log(SS_stats.income_P90/SS_stats.income_Q3); log(SS_stats.income_Q3/SS_stats.income_B10); log(SS_stats.w_P90/SS_stats.w_Q3); log(SS_stats.C_P90/SS_stats.C_B10); log(SS_stats.C_P90/SS_stats.C_Q3); log(SS_stats.C_Q3/SS_stats.C_B10); ...
				log(SS_stats.income_I_P90/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_Q3); log(SS_stats.income_I_Q3/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_B10); log(SS_stats.income_I_P90/SS_stats.income_I_Q3); log(SS_stats.income_I_Q3/SS_stats.income_I_B10); log(SS_stats.w_I_P90/SS_stats.w_I_Q3); log(SS_stats.C_I_P90/SS_stats.C_I_B10); log(SS_stats.C_I_P90/SS_stats.C_I_Q3); log(SS_stats.C_I_Q3/SS_stats.C_I_B10); ...
				log(SS_stats.MRS)   ; log(SS_stats.A_hh)   ; log(SS_stats.B_nb/(1-param.death_rate)*param.b_a_aux); log(SS_stats.Chh); ...
				log(SS_stats.N)     ; log(SS_stats.L)      ; log(SS_stats.UB)       ; ...
				log(grid.K)         ; log(SS_stats.B2)     ; log(SS_stats.B_gov_ncp); ... 
				log(SS_stats.T)     ; log(SS_stats.LT)     ; log(SS_stats.G)        ;  ...
				log(SS_stats.Lambda); log(param.pi_bar)    ; ...
				log(SS_stats.V)     ; log(SS_stats.J)      ; log(SS_stats.r_l)  ; log(SS_stats.v)   ; ...
				log(SS_stats.Y)     ; log(SS_stats.Profit) ; log(SS_stats.r_k)  ; log(SS_stats.r_a) ; log(SS_stats.mc); ...				
				log(SS_stats.u)     ; log(param.n)         ; log(SS_stats.M)    ; log(SS_stats.f) ; ...
				log(SS_stats.zz)    ; log(SS_stats.xx)     ; log(SS_stats.vv)   ; log(SS_stats.ee); log(SS_stats.C_b); log(SS_stats.Profit_FI);  ...
				log(SS_stats.R_a)   ; log(SS_stats.R)      ; log(SS_stats.I2)   ; ...
				0                   ; ...
				log(SS_stats.A_g); log(SS_stats.Y)  ; log(SS_stats.C); log(SS_stats.I2); log(param.w_bar); log(SS_stats.Profit+SS_stats.Profit_FI); ...
				log(100*param.u)     ; log(param.pi_bar); log(param.R_cb); log(param.w_bar); log(SS_stats.G); ...
				log(SS_stats.Y); log(SS_stats.Chh); log(SS_stats.I2); log(SS_stats.Profit+SS_stats.Profit_FI); log(param.u); log(SS_stats.LT); log(SS_stats.A_g); ...
				log(param.lambda); 0; 0; log(param.eta); 0; log(SS_stats.LT); log(SS_stats.G); log(SS_stats.LT); log(SS_stats.B_gov_ncp2)];  	
end																						
	

grid.maxdim = 10;

[Poly,InvCheb,Gamma2] = createSparsebasis(grid,grid.maxdim,Xss);
n1 = size(Poly); % used for controls
n2 = size(Gamma2); %used for distributions

% Produce matrices to reduce state-space

grid.os         = length(Xss) - grid.nb - grid.na - grid.nse;
grid.oc         = length(Yss) - 3*n1(1);
grid.oc_summary = 117 + 7;
grid.oc_agg     = grid.oc-grid.oc_summary;
grid.os_process = 17;
grid.os_agg     = grid.os-grid.os_process;

InvGamma                          = sparse(3*n1(1)+n2(2)+grid.os+grid.oc,3*n1(2)+n2(2)+grid.os+grid.oc);

Gamma_state                       = sparse(Gamma2);
InvGamma(1:n2(1)+grid.os,1:n2(1)+grid.os)     = eye(n2(1)+grid.os);

Gamma_control                                 = sparse(3*n1(1)+grid.oc,3*n1(2)+grid.oc);
Gamma_control(1:n1(1),1:n1(2))                = Poly;
InvGamma(n2(2)+grid.os+(1:n1(1)),n2(2)+grid.os+(1:n1(2))) = InvCheb';

Gamma_control(n1(1)+(1:n1(1)),n1(2)+(1:n1(2)))                              = Poly;
InvGamma(n2(2)+n1(1)+grid.os+(1:n1(1)),n2(2)+n1(2)+grid.os+(1:n1(2)))       = InvCheb';
Gamma_control(2*n1(1)+(1:n1(1)),2*n1(2)+(1:n1(2)))                          = Poly;
InvGamma(n2(2)+2*n1(1)+grid.os+(1:n1(1)),n2(2)+2*n1(2)+grid.os+(1:n1(2)))   = InvCheb';

Gamma_control(3*n1(1)+(1:grid.oc),3*n1(2)+(1:grid.oc))                              = eye(grid.oc);
InvGamma(n2(2)+3*n1(1)+grid.os+(1:grid.oc),n2(2)+3*n1(2)+grid.os+(1:grid.oc))       = eye(grid.oc);

InvGamma                                      = InvGamma';



grid.numstates        = length(Xss)-3;


irfshock = char('eps_01','eps_02','eps_03','eps_04','eps_05','eps_06','eps_07','eps_08','eps_09','eps_10');
grid.exog_names       = ['eps_01';'eps_02';'eps_03';'eps_04';'eps_05';'eps_06';'eps_07';'eps_08';'eps_09';'eps_10'];
grid.numstates_shocks = 10;


grid.numstates_endo   = grid.numstates - grid.numstates_shocks; 
grid.numcontrols      = 3*n1(2)+grid.oc;
grid.num_endo         = grid.numstates_endo + grid.numcontrols;


State       = zeros(grid.numstates,1);
State_m     = State;
Contr       = zeros(grid.numcontrols,1);
Contr_m     = Contr;


